instrumentation:
  root: .
  extensions:
    - .js
  default-excludes: true
  excludes:
    - "**/*.no-cover.js"
    - "**/__test__/**" #no need to instrument this test code! Things references by it remain covered.
    - "**/functions/char-indicators.js" #many indicators are not utilized so let's ignore them.
    - "**/implementation/common.js" #contains things like exception throws, not executable code
    - "**/basics/result.js" #should not be instrumented