language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
  - yarn run build
  - yarn run test
  - yarn run codecov
node_js:
  - "16.20.1"
