language: node_js
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install -g istanbul
script:
  - istanbul cover ./jrunner.js --report lcovonly -- -R spec
  - codecov
node_js:
  - "6.1"