# This is the old way to manage dependencies. More modern ways might be a lot
# faster for installing them, but this is simple and very easy to start using.
#
# We might want to upgrade to the new way at some point, but it's not a priority
nodeLinker: node-modules
npmAuthToken: ${NPM_TOKEN}
npmPublishRegistry: https://registry.npmjs.org/
npmAlwaysAuth: true

