codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
  # Notification settings
coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 90% #overall project/ repo coverage
      parjs:
        flags:
          - parjs
      char-info:
        flags:
          - char-info

flags:
  char-info:
    paths:
      - "packages/char-info/**"
      - ".github/workflows/char-info.push.yaml"
      - "yaml.lock"
      - ".*"

  parjs:
    paths:
      - "packages/parjs/**"
      - ".github/workflows/parjs.push.yaml"
      - "yaml.lock"
      - ".*"
