name: publish parjs-then
on:
  push:
    branches:
      - master
    paths:
      - "packages/parjs-then/**"
      - ".github/workflows/parjs-then.push.yaml"
      - "yaml.lock"
      - ".*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.13.0
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: SETUP COREPACK
        run: corepack enable

      - name: SETUP NODE.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.0"
          cache: yarn
          registry-url: "https://registry.yarnpkg.com"

      - name: SETUP YARN
        run: yarn set version stable

      - name: INSTALL
        run: yarn install --immutable

      - name: BUILD
        run: yarn workspaces foreach -Rpt --from '{parjs-then}' run build

      - name: LINT
        run: yarn workspace parjs-then run lint:check

      - name: TEST
        run: yarn workspace parjs-then run test:coverage

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: packages/parjs-then/coverage
          flags: parjs-then
      - name: SETUP PUBLISH TOKEN
        run: 'echo "npmAuthToken: ${NPM_TOKEN}" >> ~/.yarnrc.yml'

      - name: PUBLISH parjs-then PACKAGE
        working-directory: packages/parjs-then
        run: yarn npm publish --access public
