name: Monorepo PR
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.9.0
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: SETUP NODE.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
          cache: yarn
          registry-url: "https://registry.yarnpkg.com"

      - name: SETUP YARN
        run: |
          corepack enable
          yarn set version stable

      - name: INSTALL
        run: yarn install --immutable

      - name: BUILD
        run: yarn workspaces foreach -Rpt --from '{char-info,parjs}' run build

      - name: LINT
        run: yarn workspaces foreach -Rpt --from '{char-info,parjs}' run lint:check

      - name: TEST
        run: yarn workspaces foreach -Rpt --from '{char-info,parjs}' run test:coverage

      - name: UPLOAD COVERAGE REPORT FOR CHAR-INFO
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/char-info

      - name: UPLOAD COVERAGE REPORT FOR PARJS
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/parjs
