name: Node.js CI
on:
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version:
                    - 18.x
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: yarn
                  registry-url: "https://registry.yarnpkg.com"
            - run: yarn install --immutable
            - run: yarn build
            - run: yarn lint:check
            - run: yarn test
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
